version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=elastic-docker
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=123456
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esd01:/usr/share/elasticsearch/data
      - plugins01:/usr/share/elasticsearch/plugins
      - ./backup:/usr/share/elasticsearch/backup
      - ./elasticsearch01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./scripts:/usr/share/elasticsearch/scripts/
      - ./es.jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9200:9200
    networks:
      - esnet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es02
    restart: always
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - cluster.name=elastic-docker
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=123456
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - "es01"
    volumes:
      - esd02:/usr/share/elasticsearch/data
      - plugins02:/usr/share/elasticsearch/plugins
      - ./backup:/usr/share/elasticsearch/backup
      - ./elasticsearch02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es.jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es03
    restart: always
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01
      - cluster.name=elastic-docker
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=123456
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - "es02"
    volumes:
      - esd03:/usr/share/elasticsearch/data
      - plugins03:/usr/share/elasticsearch/plugins
      - ./backup:/usr/share/elasticsearch/backup
      - ./elasticsearch03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es.jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet

  ls01:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: ls01
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/:/usr/share/logstash/config/
    ports:
      - 9600:9600
      - 5044:5044
    networks:
      - esnet
    depends_on:
      - "es03"

  kb01:
    container_name: kb01
    image: docker.elastic.co/kibana/kibana:7.7.0
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - "es03"

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.7.0
    restart: always
    container_name: apm-server
    ports:
      - 8200:8200
    networks:
      - esnet
    volumes:
      - "./apm-server.yml:/usr/share/apm-server/apm-server.yml"
    depends_on:
      - "kb01"

volumes:
  esd01:
    driver: local
  esd02:
    driver: local
  esd03:
    driver: local
  plugins01:
  plugins02:
  plugins03:

networks:
  esnet:
